routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



  Route::get('/',
    [
      'uses' => 'PagesController@index',
      'as' => 'front'
    ]
  );
 Route::get('/show', ['uses'=>'PagesController@show_lecturer', 'as'=>'showLecturer']);


Route::group(['prefix' => 'admin'], function(){

Route::get('dashboard', [
            'uses' => 'AdminController@dashboard',
            'as' => 'admin.dashboard'
        ]);
Route::resource('faculties', 'FacultiesController');
Route::resource('subfaculties', 'SubFacultiesController');
Route::resource('lecturers', 'LecturersController');
Route::get('ajax-subcat', ["uses" => "LecturersController@getSubfaculties"]);
Route::get('lecturer', 'LecturersController@add');
Route::get('lecturer/export', 'LecturersController@exportFile');
    });

app/Lecturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lecturer extends Model
{
     public function faculties()
    {
        return $this->belongsToMany(Faculty::class);
    }
}

app/Http/Controllers/LecturersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Lecturer;
use App\Faculty;
use App\SubFaculty;
use Excel;
use App\Exports\DataExport;

class LecturersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $lecturers = Lecturer::all();
       return view('admin.lecturers.index',compact('lecturers'));
   }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $faculties = Faculty::all();
        $subfaculties = SubFaculty::all();
        return view('admin.lecturers.create',compact('faculties','subfaculties'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     $this->validate($request, [
        'name' =>'required|min:5',
        'address' =>'required',
        'email' =>'required',
        'nationality' =>'required',
        'gender' =>'required',
        'dob' =>'required',
    ]);

     $lecturer = new Lecturer;
     $lecturer->name = $request->name;
     $lecturer->phone = $request->phone;
     $lecturer->address = $request->address;
     $lecturer->email = $request->email;
     $lecturer->nationality = $request->nationality;
     $lecturer->dob = $request->dob;
     $lecturer->gender = $request->gender;
     $lecturer->faculty_id = $request->faculty_id;
     $lecturer->sub_faculty_id = $request->sub_faculty_id;
     $lecturer->save();
     session()->flash('message','Lecturer Added Successfully');
     return redirect()->route('lecturers.index');
 }

 public function getSubfaculties(Request $request)
 {
    return SubFaculty::where('faculty_id', $request->cat_id)->get();
}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $faculties = Faculty::all();
        $subfaculties = SubFaculty::all();
        $lecturer = Lecturer::find($id);
        return view('admin.lecturers.show',compact('lecturer','faculties','subfaculties'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faculties = Faculty::all();
        $subfaculties = SubFaculty::all();
        $lecturer = Lecturer::find($id);
        return view('admin.lecturers.edit',compact('lecturer','faculties','subfaculties'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request, [

       ]);

       $lecturer = Lecturer::find($id);
       $lecturer->name = $request->name;
       $lecturer->phone = $request->phone;
       $lecturer->address = $request->address;
       $lecturer->email = $request->email;
       $lecturer->nationality = $request->nationality;
       $lecturer->dob = $request->dob;
       $lecturer->gender = $request->gender;
       $lecturer->faculty_id = $request->faculty_id;
       $lecturer->sub_faculty_id = $request->sub_faculty_id;
       $lecturer->save();
       session()->flash('message','Lecturer Updated Successfully');
       return redirect()->route('lecturers.index');
   }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Lecturer = Lecturer::find($id);
        $Lecturer->delete();
        session()->flash('message','Lecturer Deleted Successfully');
        return redirect()->route('lecturers.index');
    }

     public function add()
   {
    return view('lecturer');
   }


    public function exportFile()
     {
   return Excel::download(new DataExport, 'data.csv');
     }

}

resources/views/admin/lecturers/create.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
lecturer | Create
@endsection
@section('content')

@include('pages.layouts.message')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            lecturer Table
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">lecturer Table</a></li>
            <li class="active">Data table</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <a href="{{route('lecturers.index')}}" class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">Back</a>
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">lecturer Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-8 col-md-offset-2" > 
                       
                            <form class="form form-validate" method="post"  action="{{route('lecturers.store')}}">
                                @include('admin.partials.forms.lecturer')
                                <div class="form-group">
                                    <div class="box-footer">
                                        <input class="btn btn-primary pull-right" type="submit" value="Create">
                                        <input class="btn btn-danger pull-left" type="reset" value="Reset">
                                    </div>  
                                </div>
                            </form>
                            
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection

resources/views/admin/lecturers/edit.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
lecturer | Create
@endsection
@section('content')

@include('pages.layouts.message')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            lecturer Table
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">lecturer Table</a></li>
            <li class="active">Data table</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <a href="{{route('lecturers.index')}}" class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">Back</a>
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">lecturer Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-8 col-md-offset-2" > 
                       
                            <form class="form form-validate" method="post"  action="{{route('lecturers.update', $lecturer)}}">
                                        <input type="hidden" name="_method" value="PATCH">
                                            @include('admin.partials.forms.lecturer')
                                <div class="form-group">
                                    <div class="box-footer">
                                        <input class="btn btn-primary pull-right" type="submit" value="Create">
                                        <input class="btn btn-danger pull-left" type="reset" value="Reset">
                                    </div>  
                                </div>
                            </form>
                            
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection

resources/views/admin/lecturers/index.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
Admin | lecturer
@endsection
@section('content')
@include('pages.layouts.message')

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      lecturer Table
    </h1>
    <ol class="breadcrumb">
      <li><a href="#">lecturer Table</a></li>
      <li class="active">Data table</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <a href="{{route('lecturers.create')}}"  class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">  <i class="fa fa-plus" style="padding-right:5px;"></i>Create</a>
      <div class="col-xs-12 ">
        <!-- /.box-header -->
        <!-- /.box -->
        <div class="box box-info">
          <div class="box-header">
            <h3 class="box-title text-primary">Total lecturer : {{count($lecturers)}}</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>S.N</th>
                  <th>lecturer</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Address</th>
                  <th>Nationality</th>
                  <th>DOB</th>
                  <th>Gender</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($lecturers as $lecturer)
                <tr>
                  <td>{{$loop->index+1}}</td>
                  <td>{{$lecturer->name}}</td>
                  <td>{{$lecturer->email}}</td>
                  <td>{{$lecturer->phone}}</td>
                  <td>{{$lecturer->address}}</td>
                  <td>{{$lecturer->nationality}}</td>
                  <td>{{$lecturer->dob}}</td>
                  <td>   @if($lecturer->gender == 'm')
                       {{"Male"}}
                  @elseif($lecturer->gender == "f")
                       {{"Female"}} <br>
                      @else
                       {{"Other"}} <br>
                            @endif
                      <br></td>
                      <td>
                        <a class='btn btn-info btn-xs'  style="margin-left:5px;" href="{{route('lecturers.show', $lecturer)}}"><i class="fa fa-eye"></i></a>
                        <a class='btn btn-primary btn-xs'  style="margin-left:5px;" href="{{route('lecturers.edit', $lecturer->id)}}"><i class="glyphicon glyphicon-edit"></i></a>
                        <form class="form-group" style="display: inline;"  action="{{'/admin/lecturers/'.$lecturer->id}}" onsubmit="return confirmAction('Are you sure you want to delete?')" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Delete ImageFolder" style="margin-left:5px;"><i class="glyphicon glyphicon-trash"></i></button>
                      </form>
                      </td>
                    </tr>
                    @endforeach 
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->

    <!-- DataTables -->
@endsection

resources/views/admin/lecturers/show.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
{{$lecturer->lecturer_name}}
@endsection
@section('content')
@include('pages.layouts.message')

<div class="content-wrapper">
	<section class="content-header">
		<h1>
			{{$lecturer->lecturer_name}}
		</h1>
		<ol class="breadcrumb">
			<li><a href="#">lecturer Table</a></li>
			<li class="active">Data table</li>
		</ol>
	</section>
	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box-header pull-right">
					<a href="{{route('lecturers.index')}}" class="btn btn-primary btn-sm btn-flat" >Back</a>
					<a class="btn btn-primary btn-sm btn-flat" href="{{route('lecturers.create')}}">
						<i class="fa fa-plus"></i> Add lecturer
					</a>
					<a class="btn btn-primary btn-sm btn-flat" href="{{route('lecturers.edit', $lecturer->id)}}">
						<i class="fa fa-edit"></i> Edit lecturer
					</a>
				</div>
			</div>
			<div class="col-xs-12">
				<!-- /.box-header -->
				<!-- /.box -->
				<div class="box box-info">
					<div class="box-header">
						<h3 class="box-title">{{$lecturer->lecturer_name}}</h3>
					</div>
					<br/>
					<!-- /.box-header -->
					<div class="box-body">
						<div class="col-md-8" >              
							<p><strong>ID</strong><br> {{$lecturer->id}}<br></p>
							<p class="c"><strong>Full Name</strong><br>{{$lecturer->name}} <br></p>
							<p class="c"><strong>Address</strong><br>{{$lecturer->address}} <br></p>
							<p class="c"><strong>Nationality</strong><br>{{$lecturer->nationality}} <br></p>
							<p class="c"><strong>Date Of Birth</strong><br>{{$lecturer->dob}} <br></p>
							<p><strong>Phone</strong><br>{{$lecturer->phone}} <br></p>
							<p><strong>Email</strong><br>{{$lecturer->email}} <br></p>
							<p><strong>Gender</strong><br>@if($lecturer->gender == 'm')
								{{"Male"}}
								@elseif($lecturer->gender == "f")
								{{"Female"}} <br>
								@else
								{{"Other"}} <br>
							@endif</p>
							<br/>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
</div>
@endsection