routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



  Route::get('/',
    [
      'uses' => 'PagesController@index',
      'as' => 'front'
    ]
  );
 Route::get('/show', ['uses'=>'PagesController@show_lecturer', 'as'=>'showLecturer']);


Route::group(['prefix' => 'admin'], function(){

Route::get('dashboard', [
            'uses' => 'AdminController@dashboard',
            'as' => 'admin.dashboard'
        ]);
Route::resource('faculties', 'FacultiesController');
Route::resource('subfaculties', 'SubFacultiesController');
Route::resource('lecturers', 'LecturersController');
Route::get('ajax-subcat', ["uses" => "LecturersController@getSubfaculties"]);
Route::get('lecturer', 'LecturersController@add');
Route::get('lecturer/export', 'LecturersController@exportFile');
    });

app/SubFaculty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubFaculty extends Model
{
     public function faculty()
    {
       return $this->belongsToMany(Faculty::class);
    }
}

app/Http/Controllers/SubFacultiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SubFaculty;
use App\Faculty;

class SubFacultiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $subfaculties =  SubFaculty::all();
          return view('admin.subfaculties.index', compact('subfaculties'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $faculties = Faculty::all();
        return view('admin.subfaculties.create',compact('faculties'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $subfaculty = new SubFaculty;
        $this->validate($request,[
            'subfaculty_name'=> 'required',
        ]);
            
        $subfaculty->subfaculty_name = $request->subfaculty_name;
        $subfaculty->faculty_id = $request->faculty_id;
        $subfaculty->save();
        session()->flash('message','Subfaculty Added Successfully');
        return redirect()->route('subfaculties.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faculties = Faculty::all();
        $subfaculty = SubFaculty::find($id);
        return view('admin.subfaculties.edit',compact('faculties','subfaculty'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $subfaculty = SubFaculty::find($id);
        $this->validate($request,[
            
        ]);
            
        $subfaculty->subfaculty_name = $request->subfaculty_name;
        $subfaculty->faculty_id = $request->faculty_id;
        $subfaculty->save();
        session()->flash('message','Subfaculty Updated Successfully');
        return redirect()->route('subfaculties.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subfaculty = SubFaculty::find($id);
        $subfaculty->delete();
        session()->flash('message','Subfaculty Deleted Successfully');
        return redirect()->route('subfaculties.index');
    }
}

resources/views/admin/subfaculties/create.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
subfaculty | Create
@endsection
@section('content')

@include('pages.layouts.message')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            subfaculty Table
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">subfaculty Table</a></li>
            <li class="active">Data table</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <a href="{{route('faculties.index')}}" class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">Back</a>
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">subfaculty Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-8 col-md-offset-2" > 
                       
                            <form class="form form-validate" method="post"  action="{{route('subfaculties.store')}}">
                                @include('admin.partials.forms.subfaculty')
                                <div class="form-group">
                                    <div class="box-footer">
                                        <input class="btn btn-primary pull-right" type="submit" value="Create">
                                        <input class="btn btn-danger pull-left" type="reset" value="Reset">
                                    </div>  
                                </div>
                            </form>
                            
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection

resources/views/admin/subfaculties/edit.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
lecturer | Create
@endsection
@section('content')

@include('pages.layouts.message')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            lecturer Table
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">lecturer Table</a></li>
            <li class="active">Data table</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <a href="{{route('subfaculties.index')}}" class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">Back</a>
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">lecturer Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-8 col-md-offset-2" > 
                       
                            <form class="form form-validate" method="post"  action="{{route('subfaculties.update', $subfaculty)}}">
                                        <input type="hidden" name="_method" value="PATCH">
                                            @include('admin.partials.forms.subfaculty')
                                <div class="form-group">
                                    <div class="box-footer">
                                        <input class="btn btn-primary pull-right" type="submit" value="Create">
                                        <input class="btn btn-danger pull-left" type="reset" value="Reset">
                                    </div>  
                                </div>
                            </form>
                            
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection

resources/views/admin/subfaculties/index.blade.php
@extends('admin.adminlayouts.admaster')
@section('title')
Admin | subfaculty
@endsection
@section('content')
@include('pages.layouts.message')

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      subfaculty Table
    </h1>
    <ol class="breadcrumb">
      <li><a href="#">subfaculty Table</a></li>
      <li class="active">Data table</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <a href="{{route('subfaculties.create')}}"  class="btn btn-primary pull-right" style="margin-right: 20px;margin-bottom: 10px;">  <i class="fa fa-plus" style="padding-right:5px;"></i>Create</a>
      <div class="col-xs-12 ">
        <!-- /.box-header -->
        <!-- /.box -->
        <div class="box box-info">
          <div class="box-header">
            <h3 class="box-title text-primary">Total subfaculty : {{count($subfaculties)}}</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>S.N</th>
                  <th>Subfaculty</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($subfaculties as $subfaculty)
                <tr>
                  <td> {{$loop->index+1}}</td>
                  <td> {{$subfaculty->subfaculty_name}}</td>
                      <td>
                       
                        <a class='btn btn-primary btn-xs'  style="margin-left:5px;" href="{{'/admin/subfaculties/'.$subfaculty->id.'/edit'}}"><i class="glyphicon glyphicon-edit"></i></a>
                        <form class="form-group" style="display: inline;"  action="{{'/admin/subfaculties/'.$subfaculty->id}}" onsubmit="return confirmAction('Are you sure you want to delete?')" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Delete ImageFolder" style="margin-left:5px;"><i class="glyphicon glyphicon-trash"></i></button>
                      </form>
                      </td>
                    </tr>
                    @endforeach 
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->

    <!-- DataTables -->
@endsection